apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5uZy5ibHVlbWl4Lm5ldCI6eyJ1c2VybmFtZSI6InRva2VuIiwicGFzc3dvcmQiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcWRHa2lPaUpoTlRaaU9UUmtaaTB6WVRoa0xUVTRaakF0T0RSaU5TMDRaREV6TWpsaVlXUTRZV0lpTENKcGMzTWlPaUp5WldkcGMzUnllUzV1Wnk1aWJIVmxiV2w0TG01bGRDSjkuX2hRbTVVcExDckxDWEctSGk0YUVRWU13amlhODhEMGNkNmg4Nmoxbm1IZyIsImVtYWlsIjoidG9rZW4iLCJhdXRoIjoiZEc5clpXNDZaWGxLYUdKSFkybFBhVXBKVlhwSk1VNXBTWE5KYmxJMVkwTkpOa2xyY0ZoV1EwbzVMbVY1U25Ga1IydHBUMmxLYUU1VVdtbFBWRkpyV21rd2VsbFVhR3RNVkZVMFdtcEJkRTlFVW1sT1V6QTBXa1JGZWsxcWJHbFpWMUUwV1ZkSmFVeERTbkJqTTAxcFQybEtlVnBYWkhCak0xSjVaVk0xZFZwNU5XbGlTRlpzWWxkc05FeHROV3hrUTBvNUxsOW9VVzAxVlhCTVEzSk1RMWhITFVocE5HRkZVVmxOZDJwcFlUZzRSREJqWkRab09EWnFNVzV0U0djPSJ9fX0=
kind: Secret
metadata:
  name: bluemix-default-secret
  namespace: ibmcloud-operators
type: kubernetes.io/dockerconfigjson