language: go
go:
  - "1.11"

os:
  - "linux"

services:
  - docker

before_script:
  - make deps

before_install:
  #- mkdir -p ${GOPATH}/src/github.com/ibm
  #- mv ${GOPATH}/src/github.ibm.com/seed/cloud-operators ${GOPATH}/src/github.com/ibm/cloud-operators
  #- cd ${GOPATH}/src/github.com/ibm/cloud-operators
  - source travis-env.sh

script:
  - make generate
  #- make lintall
  # - make test

after_success:
  - make push
  - test "$TRAVIS_EVENT_TYPE" != "pull_request" && make docker-build || echo "success"

#  build only master and tagged/branch releases.
branches:
  only: 
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

deploy:
  skip_cleanup: true
  provider: script
  script: bash -c "make docker-push"
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|[0-9]+\..*|v[0-9]+\..*|release-[0-9]+\..*$