apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: esindexes.ibmcloud.ibm.com
spec:
  group: ibmcloud.ibm.com
  names:
    kind: EsIndex
    plural: esindexes
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bindOnly:
              description: Bind to an existing topic if true, default value false
              type: boolean
            bindingFrom:
              description: Secret name that holds the elastic search access credentials
              type: object
            indexName:
              description: Name of Index to be created on elastic search
              type: string
            numberOfReplicas:
              description: Number of replicas, default value 1
              format: int32
              type: integer
            numberOfShards:
              description: Number of shards, default value 1
              format: int32
              type: integer
          required:
          - indexName
          - bindingFrom
          type: object
        status:
          properties:
            generation:
              format: int64
              type: integer
            message:
              type: string
            state:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: string
          required:
          - generation
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
