apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: buckets.ibmcloud.ibm.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.state
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: ibmcloud.ibm.com
  names:
    kind: Bucket
    plural: buckets
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bindOnly:
              type: boolean
            bindingFrom:
              type: object
            bucketType:
              description: Default to us-south
              type: string
            context:
              description: Default to true
              properties:
                org:
                  type: string
                region:
                  type: string
                resourcegroup:
                  type: string
                resourcelocation:
                  type: string
                space:
                  type: string
              required:
              - org
              - space
              - region
              - resourcegroup
              - resourcelocation
              type: object
            corsRules:
              description: Default to standard
              properties:
                allowedHeader:
                  description: Default to *
                  type: string
                allowedMethods:
                  description: Default to *
                  items:
                    type: string
                  type: array
                allowedOrigin:
                  type: string
              type: object
            keepIfNotEmpty:
              type: boolean
            location:
              description: Default to regional
              type: string
            resiliency:
              type: string
            retentionPolicy:
              description: ExternalInstanceID string `json:"externalInstanceId,omitempty"`
              properties:
                defaultRetentionDay:
                  format: int64
                  type: integer
                maximumRetentionDay:
                  format: int64
                  type: integer
                minimumRetentionDay:
                  format: int64
                  type: integer
              type: object
            storageClass:
              description: Default to public
              type: string
          required:
          - bindingFrom
          type: object
        status:
          properties:
            message:
              type: string
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
