apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  name: myes
spec:
  plan: standard
  serviceClass: databases-for-elasticsearch
  parameters:
  - members_disk_allocation_mb: 30720
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: binding-myes
spec:
  serviceName: myes
  role: Editor