# Constants used to package the operator for operator hub

operator_name: ibmcloud-operator
channel_name: alpha
maturity: alpha
image: registry.ng.bluemix.net/seed/cloud-operators
crd:
    - kind: Service
      description: IT Represents an instance of a Service resource on IBM Cloud.
      example: |-
        {"apiVersion": "ibmcloud.ibm.com/v1alpha1",
            "kind": "Service",
            "metadata": {
            "name": "myeventstreams"
            },
            "spec": {
            "serviceClass": "messagehub",
            "plan": "standard",
            "externalName": "myeventstreams"
            }
        }
    - kind: Binding
      description: Represents an instance of a Service binding resource on IBM Cloud. A Binding creates a secret with the service instance credentials.
      example: |-
        {"apiVersion": "ibmcloud.ibm.com/v1alpha1",
            "kind": "Binding",
            "metadata": {
            "name": "myeventstreams-binding"
            },
            "spec": {
            "serviceName": "myeventstreams"
            }
        }
    - kind: Function
      description: Represents an IBM Cloud Function action. 
      example: |-
        {"apiVersion": "ibmcloud.ibm.com/v1alpha1",
          "kind": "Function",
          "metadata": {
              "name": "greetings"
          },
          "spec": {
              "codeURI": "https://raw.githubusercontent.com/apache/incubator-openwhisk-catalog/master/packages/utils/echo.js",
              "runtime": "nodejs:6",
              "parameters": [
                {
                    "name": "message",
                    "value": "Bonjour"
                }
              ]
          }
        }
    - kind: Invocation
      description: Represents an IBM Cloud Function activation. 
      example: |-
        {"apiVersion": "ibmcloud.ibm.com/v1alpha1",
          "kind": "Invocation",
          "metadata": {
              "name": "echo-invocation"
          },
          "spec": {
              "finalizer": {
                "function": "/whisk.system/utils/echo",
                "parameters": [
                    {
                      "name": "message",
                      "value": "Bye World"
                    }
                ]
              },
              "function": "/whisk.system/utils/echo",
              "parameters": [
                {
                    "name": "message",
                    "value": "Hello World"
                }
              ]
          }
        }
    - kind: Package
      description: Represents an IBM Cloud Function package. 
      example: |-
        {"apiVersion": "ibmcloud.ibm.com/v1alpha1",
          "kind": "Package",
          "metadata": {
              "name": "mh-publish"
          },
          "spec": {
              "bind": "/whisk.system/messaging",
              "service": "message-hub"
          }
        }
    - kind: Trigger
      description: Represents an IBM Cloud Function trigger. 
      example: |-
          {"apiVersion": "ibmcloud.ibm.com/v1alpha1",
            "kind": "Trigger",
            "metadata": {
                "name": "image-uploaded"
            },
            "spec": {
                "feed": "openwhisk-cloudant/changes"
            }
          }
    - kind: Rule
      description: Represents an IBM Cloud Function rule. 
      example: |-
        {"apiVersion": "ibmcloud.ibm.com/v1alpha1",
          "kind": "Rule",
          "metadata": {
              "name": "my-rule"
          },
          "spec": {
              "action": "hello-world",
              "trigger": "image-uploaded"
          }
        }